### ISSUE TITLE
TypeError: path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by dartrax** [7Flixs/vs_code_http_server_and_html_preview#1]
Hi there,
the description looks quite promising, but I'm getting this when I try to preview a .html file:

```
TypeError: path must be absolute or specify root to res.sendFile
	at ServerResponse.sendFile (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\response.js:421:11)
	at app.use (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\out\extension.js:36:17)
	at Layer.handle [as handle_request] (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\layer.js:95:5)
	at trim_prefix (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:317:13)
	at C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:284:7
	at Function.process_params (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:335:12)
	at next (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:275:10)
	at expressInit (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\middleware\init.js:40:5)
	at Layer.handle [as handle_request] (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\layer.js:95:5)
	at trim_prefix (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:317:13)
	at C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:284:7
	at Function.process_params (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:335:12)
	at next (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:275:10)
	at query (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\middleware\query.js:45:5)
	at Layer.handle [as handle_request] (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\layer.js:95:5)
	at trim_prefix (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:317:13)
	at C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:284:7
	at Function.process_params (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:335:12)
	at next (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:275:10)
	at Function.handle (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\router\index.js:174:3)
	at Function.handle (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\application.js:174:10)
	at Server.app (C:\Users\dartrax\.vscode\extensions\flixs.vs-code-http-server-and-html-preview-1.0.2\node_modules\express\lib\express.js:39:9)
	at emitTwo (events.js:106:13)
	at Server.emit (events.js:194:7)
	at parserOnIncoming (_http_server.js:563:12)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by 7Flixs** [comment]
Hey,

can you tell how the project was build when you tried to open it, the file structure and names of your main html file.

Kind regards,

Shawn.

**Comment by dartrax** [comment]
Hi Shawn, thank you for your reply.
I just open one file:
`D:\Dropbox\eBay\_W211 Fach\Verkaufstext\Verkaufstext_First.html`

**Comment by 7Flixs** [comment]
Hey,

sorry for the late response!
Are you sure that you are in the root directory of your website, and the `"mainFile"` is edited in your config to be your actuall main file you want to launch. The default `"mainFile"` is `"index.html`, so you would have to edit that or otherwise it'll fail to find your file.

In the future i can add a feature to add a new command to launch a HTTP server with the current selected file. So if you are interested in that i can add that in the near feature when i have time spare.

Kind regards,

Shawn.

**Comment by PopFizzle** [comment]
dartrax, I ran into that same issue when I first tried it.  I had dragged and dropped a myfile.html file into VS Code from one of my dropbox directories.  You can't open the file that way, as it was unable to locate the root directory.

The filename you are working on must match the same filename you have set in the shs.mainFile setting (the default filename is index.html).  Also, you must do a File -> Open Folder and select the parent folder that contains your index.html file.

You can't do:
- Create new file "index.html"
- Enter in some simple HTML code
- Save to desktop
- Start Simple HTML Server

You can do:
- Create new file "index.html"
- Enter in some simple HTML code
- Save to desktop
- Open Folder -> Desktop
- Select the index.html file
- Start Simple HTML Server

**Comment by dartrax** [comment]
I've renamed it to index.html and opened the parent folder in VS Code, as @PopFizzle suggested. It is working and it fits my needs - thank you!

**Comment by 7Flixs** [comment]
Thanks for your suggestions! I will adjust the README in the near future to make it more clear on how to use this extension and add a feature to preview the selected file.

Kind regards,

Shawn.
